INSERT INTO dw."users" (
    id,
    firstname,
    lastname,
    gender,
    email,
    dateofbirth,
    registerdate,
    phone,
    picture,
    street,
    city,
    state,
    country,
    timezone,
    title,
    updatedate
)
SELECT id,
    firstname,
    lastname,
    gender,
    email,
    dateofbirth::timestamp,
    registerdate::timestamp,
    phone,
    picture,
    street,
    city,
    state,
    country,
    timezone,
    title,
    updatedate
FROM stage.user
ON CONFLICT (id) DO UPDATE
SET id = excluded.id,
    firstname = excluded.firstname,
    lastname = excluded.lastname,
    gender = excluded.gender,
    email = excluded.email,
    dateofbirth = excluded.dateofbirth,
    registerdate = excluded.registerdate,
    phone = excluded.phone,
    picture = excluded.picture,
    street = excluded.street,
    city = excluded.city,
    state = excluded.state,
    country = excluded.country,
    timezone = excluded.timezone,
    title = excluded.title,
    updatedate = excluded.updatedate
